[package]
name = "wasm-memprof"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.97"
instrumentor = { path = "../instrumentor" }
log = "0.4.22"
