name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: cargo install wasm-pack --version 0.13.1
      - run: make bindgen
      - run: make build
      - run: npm test
